name: test101

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Push main branch into production
      uses: codingforentrepreneurs/action-branch-to-branch@main
      with:
        dest_branch: 'Branch-dest'
        source_branch: 'Branch101'
        commit_message: 'Release production version'
    env:
     GITHUB_TOKEN: ${ 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 }
