name: Workflow-Final
'on':
 workflow_dispatch:
#  push:
#    branches:
#      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
      - name: Push main branch into production
        uses: codingforentrepreneurs/action-branch-to-branch@main
        with:
          dest_branch: Branch-dest
          source_branch: main
          commit_message: Release production version
        env: 
          GITHUB_TOKEN: '${ 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 }'
